/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ExamsBankClerkRouteImport } from './routes/exams/bank-clerk'
import { Route as ExamsSscCglRouteImport } from './routes/exams/ssc-cgl'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsBankClerkRoute = ExamsBankClerkRouteImport.update({
  id: '/exams/bank-clerk',
  path: '/exams/bank-clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsSscCglRoute = ExamsSscCglRouteImport.update({
  id: '/exams/ssc-cgl',
  path: '/exams/ssc-cgl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/exams/bank-clerk': typeof ExamsBankClerkRoute
  '/exams/ssc-cgl': typeof ExamsSscCglRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/exams/bank-clerk': typeof ExamsBankClerkRoute
  '/exams/ssc-cgl': typeof ExamsSscCglRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/exams/bank-clerk': typeof ExamsBankClerkRoute
  '/exams/ssc-cgl': typeof ExamsSscCglRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browse' | '/exams/bank-clerk' | '/exams/ssc-cgl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/exams/bank-clerk' | '/exams/ssc-cgl'
  id: '__root__' | '/' | '/browse' | '/exams/bank-clerk' | '/exams/ssc-cgl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  ExamsBankClerkRoute: typeof ExamsBankClerkRoute
  ExamsSscCglRoute: typeof ExamsSscCglRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/bank-clerk': {
      id: '/exams/bank-clerk'
      path: '/exams/bank-clerk'
      fullPath: '/exams/bank-clerk'
      preLoaderRoute: typeof ExamsBankClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/ssc-cgl': {
      id: '/exams/ssc-cgl'
      path: '/exams/ssc-cgl'
      fullPath: '/exams/ssc-cgl'
      preLoaderRoute: typeof ExamsSscCglRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  ExamsBankClerkRoute: ExamsBankClerkRoute,
  ExamsSscCglRoute: ExamsSscCglRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
